import { useEffect, useState } from 'react';
import type { AiBrief, AiPlan, LifeItem } from '@/types';
import { briefWithAi, planWithAi } from '@/lib/ai';

function SourceTag({ source }: { source: 'ai' | 'offline' }) {
  return source === 'ai' ? (
    <span className="badge brand" title="Generated by the configured AI model">
      {source === 'ai' ? 'AI generated' : ''}
    </span>
  ) : (
    <span className="badge" title="Generated on-device by NIVA's built-in engine. No network used.">
      On-device engine
    </span>
  );
}

export function BriefPanel({ items, name }: { items: LifeItem[]; name?: string }) {
  const [brief, setBrief] = useState<AiBrief | null>(null);
  const [loading, setLoading] = useState(true);
  const [key, setKey] = useState(0);

  useEffect(() => {
    let live = true;
    setLoading(true);
    void (async () => {
      const b = await briefWithAi(items);
      if (live) {
        setBrief(b);
        setLoading(false);
      }
    })();
    return () => {
      live = false;
    };
  }, [items, key]);

  return (
    <div className="ai">
      <div className="ai-head">
        <span className="ai-orb" aria-hidden="true">✦</span>
        <span style={{ minWidth: 0 }}>
          <span className="ai-title">Today's brief</span>
          <span className="ai-sub">
            {name ? `${name} · ` : ''}Prioritised from your queue, not a generic list
          </span>
        </span>
        <span className="spacer" />
        {brief ? <SourceTag source={brief.source} /> : null}
      </div>
      <div className="ai-body">
        {loading || !brief ? (
          <>
            <div className="skel skel-line" style={{ width: '85%', height: 17 }} />
            <div className="skel skel-line" style={{ width: '65%' }} />
            <div className="skel skel-line" style={{ width: '75%' }} />
          </>
        ) : (
          <div className="stack">
            <p className="ai-headline">{brief.headline}</p>
            {brief.doToday.length > 0 && (
              <div>
                <div className="sec-label">Do today</div>
                <div className="stack-sm">
                  {brief.doToday.map((s, i) => (
                    <div className="step" key={i}>
                      <span>{s}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
            {brief.doThisWeek.length > 0 && (
              <div>
                <div className="sec-label">This week</div>
                <div className="stack-sm">
                  {brief.doThisWeek.map((s, i) => (
                    <div className="tick" key={i}>
                      <span>{s}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
            {!brief.doToday.length && !brief.doThisWeek.length && (
              <p className="hint">Nothing needs action right now. Add a deadline to get a brief.</p>
            )}
            <div className="row" style={{ marginTop: 4 }}>
              <button type="button" className="btn btn-ghost btn-sm" onClick={() => setKey((k) => k + 1)} disabled={loading}>
                {loading ? <span className="spin" /> : null} Regenerate
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export function PlanPanel({ item }: { item: LifeItem }) {
  const [plan, setPlan] = useState<AiPlan | null>(null);
  const [loading, setLoading] = useState(true);
  const [run, setRun] = useState(0);

  useEffect(() => {
    let live = true;
    setLoading(true);
    void (async () => {
      const p = await planWithAi(item);
      if (live) {
        setPlan(p);
        setLoading(false);
      }
    })();
    return () => {
      live = false;
    };
  }, [item, run]);

  return (
    <div className="ai">
      <div className="ai-head">
        <span className="ai-orb" aria-hidden="true">✦</span>
        <span style={{ minWidth: 0 }}>
          <span className="ai-title">Renewal plan</span>
          <span className="ai-sub">Steps, paperwork and the traps to avoid</span>
        </span>
        <span className="spacer" />
        {plan ? <SourceTag source={plan.source} /> : null}
      </div>
      <div className="ai-body">
        {loading || !plan ? (
          <div>
            <div className="skel skel-line" style={{ width: '70%', height: 17 }} />
            <div className="skel skel-line" style={{ width: '92%' }} />
            <div className="skel skel-line" style={{ width: '84%' }} />
            <div className="skel skel-line" style={{ width: '60%' }} />
            <p className="hint" style={{ marginTop: 10 }}>Building your plan…</p>
          </div>
        ) : (
          <div className="stack">
            <p className="ai-headline">{plan.headline}</p>
            <div className="ai-lead">{plan.leadTimeNote}</div>

            <div>
              <div className="sec-label">Steps</div>
              <div className="steps">
                {plan.steps.map((s, i) => (
                  <div className="step" key={i}>
                    <span>{s}</span>
                  </div>
                ))}
              </div>
            </div>

            <div>
              <div className="sec-label">Gather these first</div>
              <div className="ticks">
                {plan.documents.map((d, i) => (
                  <div className="tick" key={i}>
                    <span>{d}</span>
                  </div>
                ))}
              </div>
            </div>

            {plan.watchOuts.length > 0 && (
              <div>
                <div className="sec-label">Watch out for</div>
                <div className="warns">
                  {plan.watchOuts.map((w, i) => (
                    <div className="warn" key={i}>
                      <span>{w}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div className="row" style={{ marginTop: 2 }}>
              <button type="button" className="btn btn-ghost btn-sm" onClick={() => setRun((r) => r + 1)} disabled={loading}>
                {loading ? <span className="spin" /> : null} Rebuild plan
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
